version: "3.3"

services:
    postgres_db:
        image: postgres
        env_file: 
            - .env
        ports:
            - "5432:5432"

    app:
        image: arkaikus/flask_api
        build: .
        env_file: 
            - .env
        ports:
            - "5000:5000"
        depends_on:
            - postgres_db
        command: flask run
